//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinnanceControll.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinnanceControll.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A transação precisa de um nome ou identificador para ser salva;.
        /// </summary>
        public static string EmptyOrNullTransactionIdentifier {
            get {
                return ResourceManager.GetString("EmptyOrNullTransactionIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Data da transação deve ser posterior a 01/01/2000..
        /// </summary>
        public static string InvalidTransactionDateTime {
            get {
                return ResourceManager.GetString("InvalidTransactionDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum TimeProvider fornecido..
        /// </summary>
        public static string NullTimeProvider {
            get {
                return ResourceManager.GetString("NullTimeProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceção não tratada capturada em {0} - DateTime: {1}..
        /// </summary>
        public static string RawException {
            get {
                return ResourceManager.GetString("RawException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A referência já está preenchida..
        /// </summary>
        public static string SingletonViolated {
            get {
                return ResourceManager.GetString("SingletonViolated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor da transação deve ser superior a zero..
        /// </summary>
        public static string TransactionValidationValueGreaterThanZero {
            get {
                return ResourceManager.GetString("TransactionValidationValueGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foram encontrados problemas no payload durante a validação..
        /// </summary>
        public static string ValidationFailure {
            get {
                return ResourceManager.GetString("ValidationFailure", resourceCulture);
            }
        }
    }
}
